### ISSUE TITLE
Broken with current litho release

### ISSUE THREAD

**Issue by yschimke** [vinc3m1/litho-kotlin#3]
ContainerBuilder no longer a thing

**Comment by vinc3m1** [comment]
Updated

**Comment by yschimke** [comment]
I think onCreate should return a Container now

**Comment by vinc3m1** [comment]
Ah a Component you mean, yes good catch. Updated.

**Comment by yschimke** [comment]
Also for your example, why wrap in braces rather than return an expression?

**Comment by vinc3m1** [comment]
Mostly the minor/stylistic reason that it's easier to add more lines to the function later.
